"""Float32 PyTorch acceleration for the project's supported PyCOL metrics."""

from .api import SUPPORTED_METRICS, PyCOLMetricsResult, compute_metrics
from .backend import Backend, resolve_backend, solve_block_size
from .distance import (
    AUTO_COMPUTE_MODE,
    FAST_COMPUTE_MODE,
    REPRODUCIBLE_COMPUTE_MODE,
    EuclideanKernel,
    HEOMKernel,
    TileKernel,
    euclidean_kernel,
    heom_kernel,
    resolve_compute_mode,
)
from .engine import DistanceTile, EngineResult, Reducer, TileEngine, duplicate_group_ids
from .features import (
    ClassFeatureStats,
    class_feature_stats,
    f1v,
    f2,
    f3,
    input_noise,
)
from .geometry import DistanceResult, GeometryResult, build_geometry, synchronize_device
from .knn import KNN_TIE_POLICY, KNNGraph, build_knn_graph
from .measures import (
    BorderlineCounts,
    NeighbourhoodCounts,
    NeighbourhoodProfile,
    borderline,
    c1,
    c2,
    cm,
    d3,
    degree_of_overlap,
    kdn,
    local_set_cardinality,
    n2,
    neighbourhood_counts,
    neighbourhood_profile,
    r_value,
    separability_index,
)
from .metrics import MetricResult, compute_f1, compute_neighbor_metrics
from .multiresolution import (
    ResolutionProfile,
    cell_assignments,
    neighbourhood_separability,
    purity,
)
from .n1 import (
    PYCOL_EDGE_CUTOFF,
    TIE_POLICY,
    N1Result,
    N1Score,
    compute_n1,
    fixed_range_scale,
    minimum_spanning_forest,
    pairwise_distances,
    resolve_device,
    score_n1,
)
from .primitives import (
    KNNPrefix,
    LocalSetSize,
    NearestEnemy,
    NearestEnemyResult,
    NearestFriend,
    TopKPrefix,
    nearest_under_mask,
    ordered_topk,
)
from .reference import compute_n1_reference
from .spheres import (
    Ball,
    ContainingSphere,
    GreedyCoverStep,
    SphereCoverage,
    dbc,
    icsv,
    nsg,
    onb,
    onb_cover,
    sphere_coverage,
    sphere_radii,
    t1,
)

__version__ = "0.2.0"

__all__ = [
    "AUTO_COMPUTE_MODE",
    "Backend",
    "Ball",
    "BorderlineCounts",
    "ClassFeatureStats",
    "ContainingSphere",
    "DistanceResult",
    "DistanceTile",
    "EngineResult",
    "EuclideanKernel",
    "FAST_COMPUTE_MODE",
    "GeometryResult",
    "GreedyCoverStep",
    "HEOMKernel",
    "KNNGraph",
    "KNNPrefix",
    "KNN_TIE_POLICY",
    "LocalSetSize",
    "MetricResult",
    "N1Result",
    "N1Score",
    "NearestEnemy",
    "NearestEnemyResult",
    "NearestFriend",
    "NeighbourhoodCounts",
    "NeighbourhoodProfile",
    "PYCOL_EDGE_CUTOFF",
    "PyCOLMetricsResult",
    "REPRODUCIBLE_COMPUTE_MODE",
    "Reducer",
    "ResolutionProfile",
    "SUPPORTED_METRICS",
    "SphereCoverage",
    "TIE_POLICY",
    "TileEngine",
    "TileKernel",
    "TopKPrefix",
    "__version__",
    "borderline",
    "build_geometry",
    "build_knn_graph",
    "c1",
    "c2",
    "cell_assignments",
    "class_feature_stats",
    "cm",
    "compute_f1",
    "compute_metrics",
    "compute_n1",
    "compute_n1_reference",
    "compute_neighbor_metrics",
    "d3",
    "dbc",
    "degree_of_overlap",
    "duplicate_group_ids",
    "euclidean_kernel",
    "f1v",
    "f2",
    "f3",
    "fixed_range_scale",
    "heom_kernel",
    "icsv",
    "input_noise",
    "kdn",
    "local_set_cardinality",
    "minimum_spanning_forest",
    "n2",
    "nearest_under_mask",
    "neighbourhood_counts",
    "neighbourhood_profile",
    "neighbourhood_separability",
    "nsg",
    "onb",
    "onb_cover",
    "ordered_topk",
    "pairwise_distances",
    "purity",
    "r_value",
    "resolve_backend",
    "resolve_compute_mode",
    "resolve_device",
    "score_n1",
    "separability_index",
    "solve_block_size",
    "sphere_coverage",
    "sphere_radii",
    "synchronize_device",
    "t1",
]
